<a href="https://colab.research.google.com/github/Daegil2/practice/blob/main/0810_Label_onehotencoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# LabelEncoder API 를 활용한 카테고리 데이터 인코딩
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('Label encoding result:',labels)



Label encoding result: [0 1 4 5 3 3 2 2]


In [4]:
# LabelEncoder API 를 활용한 카테고리 데이터 인코딩
print('Encoding classes:',encoder.classes_)
# 인코딩 된 라벨 값을 이용하여 해당 값의 클래스 정보 조회
print('Decoding values:',encoder.inverse_transform([4, 5, 2, 0, 1, 3]))


Encoding classes: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
Decoding values: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '선풍기']


In [5]:
# OneHotEncoder API
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)


In [6]:
# OneHotEncoder API 를 활용한 카테고리 데이터 인코딩
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
one_hot_encoder.fit(labels)
one_hot_labels = one_hot_encoder.transform(labels)
print(one_hot_labels.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [7]:
# StandardScaler API
# StandardScaler API 사용 전 Iris 데이터의 평균과 분산 확인
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
df_iris = pd.DataFrame(data=iris_data, columns=iris.feature_names) 
print('Average')
print(df_iris.mean())
print('\nVariance')
print(df_iris.var())

Average
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Variance
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [9]:
# StandardScaler API를 이용한 Standardization 수행
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)

In [11]:
# StandardScaler API를 이용한 Standardization 수행
df_scaled_iris = pd.DataFrame(data=scaled_iris, 
columns=iris.feature_names)
print('Average')
print(df_scaled_iris.mean())
print('\nVariance')
print(df_scaled_iris.var())

Average
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Variance
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [12]:
# MinMaxScaler API를 이용한 Normalization 수행
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)



In [14]:
# MinMaxScaler API를 이용한 Normalization 수행
df_scaled_iris = pd.DataFrame(data=scaled_iris,
columns=iris.feature_names)
print('Min value')
print(df_scaled_iris.min())
print('\nMax value')
print(df_scaled_iris.max())


Min value
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Max value
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
