<a href="https://colab.research.google.com/github/Daegil2/practice/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
imputer = SimpleImputer(strategy = "most_frequent")
x_train = np.array([100,200,300,np.NaN, 300, np.NaN]).reshape(-1,1)
x_test= np.array([100,300,500,np.NaN, np.NaN, np.NaN]).reshape(-1,1)
x_train


array([[100.],
       [200.],
       [300.],
       [ nan],
       [300.],
       [ nan]])

In [ ]:
x_train_imputed = imputer.fit_transform(x_train)
# train "fit" 평균값, 최빈값, 이런것들이 imputer 모델에 저장됨
# 데이터를 전처리하고 나중에 후처리 전처리한 데이터를 다시 복원할일이 꼭 발생하는데
# Train,/test 사용한 지표가 다르면 원인도 찾기 힘들뿐 복원도 잘안됨
x_test_imputed =imputer.transform(x_test) #
print(x_train_imputed)
print(x_test_imputed)


[[100.]
 [200.]
 [300.]
 [300.]
 [300.]
 [300.]]
[[100.]
 [300.]
 [500.]
 [300.]
 [300.]
 [300.]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
items= ['TV','냉장고','모니터','냉장고','모니터']
encoder =LabelEncoder()
labels =encoder.fit_transform(items)
test = ['김치냉장고']

print(items)

['TV', '냉장고', '모니터', '냉장고', '모니터']


In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
labels =labels.reshape(-1,1)
one_hot_encoder =OneHotEncoder()
one_hot_encoder.fit(labels)
one_hot_labels = one_hot_encoder.transform(labels)

one_hot_encoder.fit(labels)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [ ]:
print('one_hot: \n', one_hot.toarray())

NameError: ignored

In [ ]:
#표준화 scaling
from sklearn.datasets import load_iris
import pandas as pd

In [ ]:
iris =load_iris()
df =pd.DataFrame(data=iris.data, columns =iris.feature_names)

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
print('Mean: ', df.mean())
print('Standard deviation:', df.std())

Mean:  sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
Standard deviation: sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [ ]:
# StandaradScaler를 통한 데이터 정규화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaler.fit(df)
scaled_iris =scaler.transform(df)

In [ ]:
df_scaled_iris =pd.DataFrame(data=scaled_iris, columns =iris.feature_names)
print(df_scaled_iris.mean())
print(df_scaled_iris.std())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler =MinMaxScaler()
scaler.fit(df_iris)
